# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "docker" # Resources - Dotnet
    directory: "/resources/runtimes/dotnetcore" # Location of package manifests
    schedule:
      interval: "weekly" 
  - package-ecosystem: "maven" # Resources - Java
    directory: "/resources/runtimes/java/code"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker" # Resources - NodeJS
    directory: "/resources/runtimes/nodejs"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm" # Resources - NodeJS
    directory: "/resources/runtimes/nodejs"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker" # Resources - PHP
    directory: "/resources/runtimes/php"
    schedule:
      interval: "weekly"
  - package-ecosystem: "composer" # Resources - PHP
    directory: "/resources/runtimes/php/code"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker" # Resources - Python
    directory: "/resources/runtimes/python"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip" # Resources - Python
    directory: "/resources/runtimes/python"
    schedule:
      interval: "weekly"


 
