# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/Labs/Module2/final/ruby"
    schedule:
      interval: "weekly"

  - package-ecosystem: "bundler"
    directory: "/resources/runtimes/ruby"
    schedule:
      interval: "weekly"

  - package-ecosystem: "composer"
    directory: "/Labs/Module2/final/php/code"
    schedule:
      interval: "weekly"

  - package-ecosystem: "composer"
    directory: "/resources/runtimes/php/code"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/Labs/Module2/final/dotnetcore"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/Labs/Module2/final/go"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/Labs/Module2/final/java/docker"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/Labs/Module2/final/nodejs"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/Labs/Module2/final/php"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/Labs/Module2/final/python"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/Labs/Module2/final/ruby"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/Labs/Module3/Multicontainers/client"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/Labs/Module3/Multicontainers/server"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/resources/runtimes/dotnetcore"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/resources/runtimes/go"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/resources/runtimes/java/docker"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/resources/runtimes/nodejs"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/resources/runtimes/php"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/resources/runtimes/python"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/resources/runtimes/ruby"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "weekly"

  - package-ecosystem: "maven"
    directory: "/Labs/Module2/final/java/code"
    schedule:
      interval: "weekly"

  - package-ecosystem: "maven"
    directory: "/resources/runtimes/java/code"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/Labs/Module2/final/nodejs"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/Labs/Module3/Multicontainers/client"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/Labs/Module3/Multicontainers/server"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/resources/runtimes/nodejs"
    schedule:
      interval: "weekly"

  - package-ecosystem: "nuget"
    directory: "/Labs/Module2/final/dotnetcore/code"
    schedule:
      interval: "weekly"

  - package-ecosystem: "nuget"
    directory: "/resources/runtimes/dotnetcore/code"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/Labs/Module2/final/python"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/resources/runtimes/python"
    schedule:
      interval: "weekly"
